import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Box from "../components/BoxServices/BoxService";
import HomeAnimation from "../components/HomeAnimation/HomeAnimation";
import styles from "../styles/pageStyles.module.css";
import Texts from "../components/serviceBoxes/serviceBoxTexts";
import ServiceBox from "../components/serviceBoxes/ServiceBox";

const Home: NextPage = () => {
  const [isClicked, setIsClicked] = useState<boolean>(false);

  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <HomeAnimation isClicked={isClicked} />
        <pre
          onClick={() => setIsClicked(true)}
          className={isClicked ? styles.animationButtonClicked : styles.animationButton}
        >
          {`
Touch 
here`}
        </pre>
        <pre className={isClicked ? styles.starsTextActive : styles.starsTextNotActive}>
        {`
          You,
       you are
       the star
        `}
        </pre>
        <main className={styles.container}>
          <div>
            <div className={styles.marginControl}></div>
            <Box title={"Augmented Reality"} type={"black"} />
            <Box type={"gray"} />
          </div>
          <div>
            <Box type={"gray"} />
            <Box title={"Mobile Applications"} type={"black"} />
            <Box title={"We make Technology more Human"} type={"empty"} />
            <Box title={"Online Shops, Web&More"} type={"black"} />
          </div>
        </main>
      </div>
      <ServiceBox
        title={Texts[0].title}
        para={Texts[0].para}
        spanReady={Texts[0].spanReady}
      />
      <ServiceBox
        title={Texts[1].title}
        para={Texts[1].para}
        spanReady={Texts[1].spanReady}
      />
    </div>
  );
};

export default Home;
